```{r}

#install.packages("Rtsne") # Install Rtsne package from CRAN
library("Rtsne")
install.packages("matrixStats")
library("matrixStats")
```

Define Important Variables

```{r}
input_counts = "C:\\Users\\Roman\\Documents\\Work\\Depression_and_Immunology\\Data\\genecounts.variancestabilized.csv"
input_annot = "C:\\Users\\Roman\\Documents\\Work\\Depression_and_Immunology\\Scripts\\Data\\meta_data_with_paths_all_patients_final.csv"
```
Import file list that contains the location of all the files
Also import a file with the samples and the sample names

```{r}

colVars <- function(x) {
  return (colSums((x - colMeans(x))^2)/(dim(x)[1] - 1))
}


```

```{r}
# let's get the file

# Read a txt file and convert gene names (first column) into indeces
my_data <- read.csv(input_counts, header = TRUE, row.names = 1, check.names = FALSE)

# Read a text file and create indeces
annot <- read.csv(input_annot, header = TRUE, row.names = 1, check.names = FALSE )

# Transpose data table
gene_df <- t(my_data)

# Convert transposed table into a data frame
gene_df <- data.frame(gene_df)


gene_df <- gene_df[rownames(annot),]
gene_df <- gene_df[complete.cases(gene_df), ] # remove rows with NaN, I think there is 1 like that

#apply(gene_df), RowVar(m)

#columnVariance
copyOfGeneDf <- gene_df
columnVariance = colVars(gene_df)
```

```{r}
gene_df <- copyOfGeneDf
# remove stuff we don't want

dim(gene_df)

#sapply(gene_df,function(x){!all(x<1)})
#colMeans(gene_df)
# gene_df <- gene_df[which(colMeans(gene_df) < 5)]
columnVariance[1]
#gene_df <- gene_df[which(colVars(gene_df) > .3),]
hist(columnVariance)
dim(gene_df)
#head(gene_df)
# make a histogram
#hist(colVars(gene_df), xlim= c(0, 1), breaks = c(0,.25,.5,.75,1,20))

```

nohup Rscript t-sne.r &

```{r}

png("t-snePlot perplexity 10.png")
labels <- rownames(gene_df)
colors = rainbow(length(unique(labels)))
names(colors) = unique(labels)
tsne_model = Rtsne(gene_df[2:40,100], perplexity=5, verbose=TRUE, check_duplicates=FALSE) # be careful with downstream

plot.new()
plot(tsne_model$Y,  t='n',main='Tsne')
text(tsne_model$Y, labels=labels, col=colors[labels])

dev.off()

```
